# Generated by Django 6.0.3 on 2026-05-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_builder', '0017_company_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Shown in PDF as the category heading')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Checkbox Categories',
                'db_table': 'form_checkbox_categories',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('work_types', 'Work Types'), ('accreditations', 'Accreditation'), ('operating_areas', 'Operating Area'), ('vehicle_types', 'Vehicle Types'), ('special_cargo', 'Special Cargo'), ('nhvr_configurations', 'NHVR Vehicle Configurations'), ('safety_policies', 'Safety Management Policies'), ('compliance_practices', 'Subcontractor Compliance Practices'), ('reporting_process', 'Incident Reporting Process')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, help_text='Shown in PDF beneath the section heading')),
                ('has_categories', models.BooleanField(default=False, help_text='True only for sections like NHVR where checkboxes are grouped into accordion categories')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'form_sections',
                'ordering': ['tab__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('operations', 'Operations'), ('fleet', 'Fleet Information'), ('risk', 'Risk Assessment'), ('subcontractors', 'Subcontractor Management'), ('incidents', 'Incident History')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, help_text='Shown in PDF beneath the tab heading')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'form_tabs',
                'ordering': ['order'],
            },
        ),
        migrations.RenameField(
            model_name='companyfleet',
            old_name='average_vehicle_age',
            new_name='average_age',
        ),
        migrations.RemoveField(
            model_name='companyoperation',
            name='audit_date_none',
        ),
        migrations.RemoveField(
            model_name='companyoperation',
            name='audit_date_trucksafe',
        ),
        migrations.RemoveField(
            model_name='companyoperation',
            name='audit_date_wahva',
        ),
        migrations.RemoveField(
            model_name='companyfleet',
            name='nhvr_configurations',
        ),
        migrations.RemoveField(
            model_name='companyfleet',
            name='special_cargo',
        ),
        migrations.RemoveField(
            model_name='companyfleet',
            name='vehicle_types',
        ),
        migrations.RemoveField(
            model_name='companyincidentprofile',
            name='reporting_process',
        ),
        migrations.RemoveField(
            model_name='companyoperation',
            name='accreditations',
        ),
        migrations.RemoveField(
            model_name='companyoperation',
            name='operating_areas',
        ),
        migrations.RemoveField(
            model_name='companyoperation',
            name='work_types',
        ),
        migrations.RemoveField(
            model_name='companyriskprofile',
            name='safety_policies',
        ),
        migrations.RemoveField(
            model_name='companysubcontractorprofile',
            name='compliance_practices',
        ),
        migrations.CreateModel(
            name='CheckboxOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Short label shown next to the checkbox', max_length=255)),
                ('value', models.CharField(help_text='Stable identifier; keep short, no spaces preferred', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Long description used when generating the PDF')),
                ('requires_date', models.BooleanField(default=False, help_text='If true, selecting this option requires an audit/related date')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Required only if the section uses categories (e.g. NHVR)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sms_builder.checkboxcategory')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sms_builder.section')),
            ],
            options={
                'db_table': 'form_checkbox_options',
                'ordering': ['section', 'category__order', 'order'],
                'unique_together': {('section', 'value')},
            },
        ),
        migrations.CreateModel(
            name='CompanyAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(blank=True, help_text='Populated only when option.requires_date is True', null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditation_entries', to='sms_builder.companyoperation')),
                ('option', models.ForeignKey(limit_choices_to={'is_active': True, 'section__key': 'accreditations'}, on_delete=django.db.models.deletion.CASCADE, to='sms_builder.checkboxoption')),
            ],
            options={
                'verbose_name': 'Company Accreditation',
                'verbose_name_plural': 'Company Accreditations',
                'db_table': 'company_accreditation_entries',
                'unique_together': {('operation', 'option')},
            },
        ),
        migrations.AddField(
            model_name='checkboxcategory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sms_builder.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sms_builder.tab'),
        ),
        migrations.AddField(
            model_name='companyfleet',
            name='nhvr_configurations',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'section__key': 'nhvr_configurations'}, related_name='fleet_nhvr_configs', to='sms_builder.checkboxoption'),
        ),
        migrations.AddField(
            model_name='companyfleet',
            name='special_cargo',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'section__key': 'special_cargo'}, related_name='fleet_special_cargo', to='sms_builder.checkboxoption'),
        ),
        migrations.AddField(
            model_name='companyfleet',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'section__key': 'vehicle_types'}, related_name='fleet_vehicle_types', to='sms_builder.checkboxoption'),
        ),
        migrations.AddField(
            model_name='companyincidentprofile',
            name='reporting_process',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'section__key': 'reporting_process'}, related_name='inc_reporting_process', to='sms_builder.checkboxoption'),
        ),
        migrations.AddField(
            model_name='companyoperation',
            name='accreditations',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'section__key': 'accreditations'}, related_name='ops_accreditations', through='sms_builder.CompanyAccreditation', to='sms_builder.checkboxoption'),
        ),
        migrations.AddField(
            model_name='companyoperation',
            name='operating_areas',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'section__key': 'operating_areas'}, related_name='ops_operating_areas', to='sms_builder.checkboxoption'),
        ),
        migrations.AddField(
            model_name='companyoperation',
            name='work_types',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'section__key': 'work_types'}, related_name='ops_work_types', to='sms_builder.checkboxoption'),
        ),
        migrations.AddField(
            model_name='companyriskprofile',
            name='safety_policies',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'section__key': 'safety_policies'}, related_name='risk_safety_policies', to='sms_builder.checkboxoption'),
        ),
        migrations.AddField(
            model_name='companysubcontractorprofile',
            name='compliance_practices',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'section__key': 'compliance_practices'}, related_name='sub_compliance_practices', to='sms_builder.checkboxoption'),
        ),
    ]
